### ISSUE TITLE
Misaligned Memory Access with GCC Optimizations (-O2) on RISC-V despite -mstrict-align

### ISSUE THREAD

**Issue by tarik-ibrahimovic** [chili-chips-ba/wireguard-fpga#5]
**Issue Summary:**

Enabling GCC optimizations (e.g., `-O2`) for our RISC-V project results in program failures due to misaligned memory accesses, despite using the `-mstrict-align` flag. Disabling optimizations (`-O0`) leads to increased binary size and reduced performance.

**Performance Impact:**

- **Without Optimizations (`-O0`):**
  - Binary Size: ~4 KB
  - Performance: 8.87 DMIPS

- **With Optimizations (`-O2`):**
  - Binary Size: ~2.8 KB
  - Performance: 24.15 DMIPS

This indicates a potential performance gain of approximately 2.7x when optimizations are enabled.

**Observed Behavior:**

Despite applying the `-mstrict-align` flag, GCC generates misaligned memory accesses under optimization levels like `-O2`, leading to program crashes. This issue has been reported in the RISC-V GCC community but persists in our case.

**Current Workaround:**

Configuring PicoRV32 with `.CATCH_MISALIGN(0)` has mitigated the issue in our specific scenario, similar to the approach used in eduBOS5. However, this solution may not be universally applicable across different programs.

**Concerns:**

Disabling optimizations to avoid misaligned accesses results in larger binaries and decreased performance. Although we transition to more potent platforms, the absence of optimizations could lead to CPU-software performance bottlenecks, as previously experienced with PicoRV32 handling two ADC channels in the Gowin Arora configuration.

**Request for Input:**

We seek guidance on addressing this misaligned memory access issue when using GCC optimizations for RISC-V. Goal is to achieve optimal performance without compromising program stability.

**References:**

- [GCC Bugzilla Report on Misaligned Memory Access](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107339)

I would appreciate any insights or recommendations from the community.

**Comment by chili-chips-ba** [comment]
@wyvernSemi does this have implications on our ISS?!

In other words, can the model be configured to match the functionality of our target RISC-V core in terms of its support, or the lack thereof, for the miss-aligned bus accesses?

While some cores fail silently for those, the others may trigger a trap that invokes software handling of these rather rare and odd transactions. And some cores include partial, or even full handling of such requests in hardware. 

It'd be cool if we could configure the ISS to match these options...

**Comment by wyvernSemi** [comment]
From my understanding this is an issue of the RISC-V gcc toolchain, and the rv32 ISS will trap on a misaligned exception as would any compliant RISC-V implementation. There's a reference to a <tt>.CATCH_MISALIGNED(0)</tt> configuration, but I'm not sure what this does. I'd assume it is disabling traps on misaligned data. This would seem dangerous as one may not read or write the data that was intended, or stomp over other data, if the access straddles an alignment boundary, depending on the logic implementation.

I'm reluctant to add this to rv32 ISS as it might be disabled and then raise support requests when code does not behave as expected. It could also be a Pandora's Box to start modelling non-compliant configurations for different RISC-V implementations in the ISS. I can (and have already, such as configuration of the timing model) add features that are generic, and remain as per the RISC-V specifications, for WireGuard, but I don't really want to make unique project specific customisations, unless there's a means to do it externally to the ISS source code (such as the discussed external class which can update the ISS timing model for a selection of pre-configured instruction delay values, or an external cache timing model to calculate user memory access callback function wait state return values).

If this is 'rare' then, depending on what is expected to happen, this could be handled as an exception. The simplest thing is if it is okay for nothing to happen (if it's a bad access, say, that's always at the end/beginning of a block containing flush/pad data only). In which case some assembly ISR code for the particular trap can simply return to the instruction after the bad access. At the other end of processing, it could read the instruction causing the trap (the address is in the <tt>mepc</tt> CSR register) and decode it (for load/store, access size, register indexes, and any immediate value), calculate the address and (for writing) the data to be stored and might turn this into a series of byte accesses. This would still be quite efficient, I think, depending on the frequency of traps. The ISR code would still be very  much smaller than the difference between non-optimised and optimised code. I'm guessing RISC-V gcc isn't likely to be fixed anytime soon.

**Comment by chili-chips-ba** [comment]
Our understanding is that this is about two separate issues:
______
1) RISC-V hardware may, or may not support misaligned accesses, see [RISC-V ISA Manual](https://five-embeddev.com/riscv-user-isa-manual/Priv-v1.12/zam.html). Should former be the case, the CPU won't trap for them. In the latter case, the CPU must trap for them. 

- Consequently, for accurate sim, the ISS should be configurable and allow both options. 

![image](https://github.com/user-attachments/assets/647aa1f6-27d2-4515-8d55-2370b59255b4)

2) 
.CATCH_MISALIGNED(0) is indeed PicoRV21 the other hand, if it does not support them in hardware, it will trap for them. oes not support them, it is supposed to raise trap.

**Comment by allenjbaum** [comment]
A misaligned write has (at least) 7 legal results, depending on 
 - whether misaligned accesses are supported or not, 
 - what the granularity of misalignment is (i.e the  power of 2 boundary crossing that is considered misaligned)
 - whether both halves of the access can be legally written (based on page table or PMP permissions), 
 - what the relative priority is between misaligned access and page fault/illegal access (high or lower is allowed)
 - which order the two halves are accessed
 - if both upper and lower are not legally accessible, which half has higher priority
 
All this assumes that the above parameters don't change dynamically (I don't think anything prevents it)
Note that it is possible to write only one half if the other half is not legal to write - and which half will or will not be written is dependent on the order of the accesses.

But, given a proper handler, you can emulate the store (except for the case where one half is legal and the other isn't - but that's likely a fatal exception in any case. Otherwise user code can't tell the difference, except through timing.

**Comment by allenjbaum** [comment]
Oh, and the 7 results (as seen by priv code) is 
 store succeeds (both halves written) (case )
 one half succeeds, one half store fails (one half written, the other half gets a trap (case2,3)
 one half succeeds, one half store fails (nothing written, fault reported in upper or lower)(case4,5)
 neither half suceeds (nothing written, fault in upper half or lower half (case6,7)

**Comment by wyvernSemi** [comment]
The quoted misaligned behaviour above appears to be for the Zam extension to atomic operations, not a general specification. The ISS does not support Zam.

**Comment by chili-chips-ba** [comment]
@allenjbaum -- How popular, or not, is the `Zam` extension? Are there actually processors that support it in hardware?

Given your explanation, the Zam seems awfully complicated and expensive for implementation in gates, and even then it may need software assist.

The reason for asking is to understand the extent of loss that comes from our ISS currently not appreciating the Zam extension.

**Comment by allenjbaum** [comment]
I'm not sure if any do for exactly the reason you allude to. (that doesn't
mean there aren't any, I'm just not aware of any.)
There is a different extension, I think, that effectively supercedes Zam by
establishing an atomic granularity.
IT defines a power of 2 boundary, such that any access that doesn't cross
the boundary will be atomic.

**Comment by chili-chips-ba** [comment]
Thank you @allenjbaum for these insights 👍. With that, we can state that our ISS is fully applicable to the vast majority of RISC-V cores out there, and certainly for the entry-level one we intend to use on this project.

With that, the attention is moving back to what we believe is GCC mishandling of `-O2` (and above) optimizations in the presence of `-mstrict-align` request.

@tarik-ibrahimovic, GCC folks are waiting for our input related to [Bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117573) item that was created for this case...

**Comment by wyvernSemi** [comment]
For the record, and just to clear up any misunderstandings, adding any extensions to atomic operations have absolutely no bearing on the RV32I load and store instructions which, I believe, is the issue Tarik posted originally.

I've suggested software based solutions, but I've seen no acknowledgement or critique of these. I've also seen no explanation of what the cores that support the turning off of misaligned traps actually do when a load/store is misaligned, so that software exception code could emulate this. If it's to treat them as `nop` instructions then the only slight complexity I see is, if using compressed instructions, to check whether the trapping load/store instruction is compressed or not (lower two bits not 11b for compressed) so that the return address (in `mepc`) is incremented by 2 or 4 before `mret`.

**Comment by chili-chips-ba** [comment]
> "... I've suggested software based solutions, but I've seen no acknowledgement or critique of these..."

It seems that the software solution is pretty much the only game in the town.

> "... no explanation of what the cores that support the turning off of misaligned traps actually do when a load/store is misaligned..."

PicoRV32 `.CATCH_MISALIGNED(0)` will ignore the misalignment, not raising an interrupt, and simply move on. That's essentially a `nop`. Since PicoRV32 also supports the `C` extension, it'd be interesting to see what it does for the 2 vs 4 address increment corner case when configured not to catch the misalignment.

**Comment by wyvernSemi** [comment]
Here is the sort of trap code I think would do the job. It processes instruction misalignments as well, but that need not be there as turning an instruction into a `nop` might cause confusion. If there's already some service routines in the crt0/boot code it might be patched into there.

```
# Setting up trap handler
  csrw mie,   zero                          # Disable all interrupt sources
  la   x1,    __align_trap_handler          # Configure trap handler
  csrw mtvec, x1

# -----------------------------------------------------
#  Trap handler for turning misaligned traps into nops
.balign 4                                   # Needs to be 32-bit aligned
__align_trap_handler:

# Push clobbered registers (x8 and x9) to stack
  addi  sp,   sp, -8
  sw    x8,   0(sp)
  sw    x9,   4(sp)

  csrr  x8,   mcause                        # Get value of mcause register
  beq   x8,   zero, __process_misaligned    # Process if instruction address misaligned (mcause = 0)
  addi  x9,   zero, 4                       # Set x9 for load address misaligned mcause
  beq   x8,   x9, __process_misaligned      # Process if load address misaligned (mcause = 4)
  addi  x9,   zero, 6                       # Set x9 for store address misaligned mcause
  beq   x8,   x9, __process_misaligned      # Process if store address misaligned (mcause = 6)

  beq   zero, zero, __other_trap_code       # Skip if not misaligned trap

# Update mepc to skip instruction that trapped
__process_misaligned:
  csrr  x8,   mepc                          # Get address of trapping instruction from mepc
  lh    x9,   0(x8)                         # Fetch lower 16 bits of instruction that caused exception
  andi  x9,   x9, 3                         # Mask lowest 2 opcode bits (11b for uncompressed instructions)

  addi  x8,   x8, +2                        # Add 2 to mepc for compressed instructions
  csrw  mepc, x8                            # Set new return address

  addi  x8,   zero, 3                       # set x8 to 11b
  bne   x8,   x9, __trap_handler_end        # Finish if a compressed instruction (not 11b)

  csrr  x8,   mepc                          # Get mepc (already incremented by 2)
  addi  x8,   x8, +2                        # Add another 2 to mepc for uncompressed instructions
  csrw  mepc, x8                            # Update mepc

__trap_handler_end:

# Pop clobbered registers from stack
  lw    x8,   0(sp)
  lw    x9,   4(sp)
  addi  sp,   sp, +8

  mret

__other_trap_code:
  nop
```

**Comment by chili-chips-ba** [comment]
On [GCC Bugzilla](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117573) discussion track @pinskia mentions:
> "... it looks like the value was corrupted somehow; I don't think the bug is due to the access there, but rather somewhere else the value of `Ptr_Val_Par->Ptr_Comp` is changing to be incorrect. Since you are working on a simulator, have you looked at where the value of _Ptr_Val_Par->Ptr_Comp_ gets changed? Does it look reasonable? ..."

2 cents from @ZipCPU:
> "... debugging GCC is doable, but takes a bunch of work. The first step is to compile to assembly.  The second step is to add the flag `-fdump-rtl-all`.  Then you look through the many debug/dump files that will be produced to find the first one with the error. That'll then point you to where in GCC (i.e. which pass) that the bug is introduced. Knowing the internal RTL language GCC uses is quite the skill..."

With that, the next steps could be to try:
- compiling the same source with `-O2 -fdump-rtl-all -mstrict-align`
- running this troublesome binary in the @wyvernSemi ISS

**Comment by regymm** [comment]
I'm not an expect in this, but maybe it's worth trying the -Os option for size optimized code? 
And it seems -O2 is a combination of [these parameters](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-O2), we can potentially find out which exactly caused this problem. 

Btw, does the "misaligned" means non-32-bit access at aligned addresses, like lh on address 0x2, or lb on 0x1. Or it's "really" misaligned like lw on address 0x2/0x1, or lh on 0x1? If it's the former case, then it's allowed by the toolchains, but will cause an error if the CPU doesn't support it.

**Comment by allenjbaum** [comment]
Misalign should refer to any access that isn't naturally aligned, so the
former case, but there is an atomicity granule PMA that defines the address
bit boundary that, if not crossed by an access, the access is guaranteed to
(appear to?) be atomic.
E.g if the bit boundary is 6 (an aligned 64B region), then if all bytes of
an access are contained within that boundary, the access must  (appear to?)
be atomic.
I *think* that implies that non-atomic accesses won't trap even if not
naturally aligned, but I'm not sure - and I don't know if GCC knows
anything about that parameter.

**Comment by regymm** [comment]
Probably -mstrict-align only prevents the second case. The CPU's capability (more likely, the bus' capability) may disallow even "aligned" non-32-bit access. 
As a check, maybe comparing the compiled binary (disassembled) could give some insights? I imagine 16-bit and 8-bit R/W may only appear in -O2 code.

**Comment by wyvernSemi** [comment]
@tarik-ibrahimovic I've been trying to compile the code, to run on the ISS, using "_the exact command used for compilation_" as per the [bugzilla comment](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117573#c4), but its compiling Dhrystone files that aren't checked in to the WireGuard repository. It implies they should be in `2.sw/app` (`dhry.h`, `dhry_1.c` and `dhry_2.c`). I have downloaded some versions of these but I don't know if they will be the exact same code---and I get compilation errors:

```
.//dhry_1.c:52:17: error: conflicting types for 'times'; have 'int()'
   52 | extern  int     times ();
      |                 ^~~~~
In file included from .//dhry.h:366,
                 from .//dhry_1.c:18:
/opt/riscv/riscv64-unknown-elf/include/sys/times.h:24:9: note: previous declaration of 'times' with type 'clock_t(struct tms *)' {aka 'long unsigned int(struct tms *)'}
   24 | clock_t times (struct tms *);
      |         ^~~~~
.//dhry_1.c: In function 'main':
.//dhry_1.c:54:27: error: 'HZ' undeclared (first use in this function)
   54 | #define Too_Small_Time (2*HZ)
      |                           ^~
.//dhry_1.c:270:19: note: in expansion of macro 'Too_Small_Time'
  270 |   if (User_Time < Too_Small_Time)
      |                   ^~~~~~~~~~~~~~
.//dhry_1.c:54:27: note: each undeclared identifier is reported only once for each function it appears in
   54 | #define Too_Small_Time (2*HZ)
      |                           ^~
.//dhry_1.c:270:19: note: in expansion of macro 'Too_Small_Time'
  270 |   if (User_Time < Too_Small_Time)
```

Dhrystone has lots of flags. Are any of them supposed to be set? They are not on the compilation command as per the bugzilla comment. Has there been any manual modification of the files? In order to proceed I need the exact files and the exact build process. If you're worried about checking in 'sandbox' files, you might create a branch of the WireGuard repo (call it 'sandbox' say) and check-in the modified files there.

**Comment by tarik-ibrahimovic** [comment]
@wyvernSemi I’ve made some manual modifications to those files, so I've created the `sandbox` branch as per your suggestion. Additionally, I’ve updated the simulation makefile to make the misalignment error directly reproducible with the following steps:

```
cd 3.build
make sw_all
cd ../4.sim
make
``` 

The misalignment error will appear in the log.

**Comment by wyvernSemi** [comment]
I believe there is a bug in the program. The `dhry_1.c` file appears to be modified from versions I can find on the internet. The failing code starts like the following:
```
/* Global Variables: */

Rec_Pointer     Ptr_Glob,
                Next_Ptr_Glob;

main ()
/*****/

  /* main program, corresponds to procedures        */
  /* Main and Proc_0 in the Ada version             */
{
        One_Fifty       Int_1_Loc;
  REG   One_Fifty       Int_2_Loc;
        One_Fifty       Int_3_Loc;
  REG   char            Ch_Index;
        Enumeration     Enum_Loc;
        Str_30          Str_1_Loc;
        Str_30          Str_2_Loc;
  REG   int             Run_Index;
  REG   int             Number_Of_Runs;

  /* Initializations */

/*   Next_Ptr_Glob = (Rec_Pointer) malloc (sizeof (Rec_Type));
  Ptr_Glob = (Rec_Pointer) malloc (sizeof (Rec_Type)); */
  Rec_Type Next_glob;
  Rec_Type Glob;

  Rec_Pointer Next_Ptr_Glob = & Next_glob;
  Rec_Pointer Ptr_Glob      = & Glob;
```

There are two global pointers, `Ptr_Glob` and `Next_Ptr_Glob`. The commented out assignments to these with `malloc` are replaced with local declarations of `Rec_Type` and the address for these are assigned to _local_ declarations of `Rec_Type` pointers, `Ptr_Glob` and `Next_Ptr_Glob`. These mask the global versions in the local scope. However, direct reference to the `Ptr_Glob` global pointer is made in `Proc_1()` in the `structassign` line.

```
Proc_1 (Ptr_Val_Par)
/******************/

REG Rec_Pointer Ptr_Val_Par;
    /* executed once */
{
  REG Rec_Pointer Next_Record = Ptr_Val_Par->Ptr_Comp;  
                                        /* == Ptr_Glob_Next */
  /* Local variable, initialized with Ptr_Val_Par->Ptr_Comp,    */
  /* corresponds to "rename" in Ada, "with" in Pascal           */
  
  structassign (*Ptr_Val_Par->Ptr_Comp, *Ptr_Glob);
```
The global `Ptr_Glob` is never assigned a value and is zero. Therefore it points to the first instruction of the `boot_crt` code:

```

main.elf:     file format elf32-littleriscv


Disassembly of section .text:

00000000 <_boot_crt>:
   #-TODO :
   #-TODO : end_copy_text:

.endif


   0:	00000517          	auipc	a0,0x0
   4:	76c50513          	addi	a0,a0,1900 # 76c <_idata_start>
``` 

This happens to have a value of `0x00000517` and this is the address value that is attempted to use for a word access.

**Comment by chili-chips-ba** [comment]
Any explanation on why `-O2` is turning this bug into a deal killer?

**Comment by ZipCPU** [comment]
Ptr_Glob should point somewhere.  In the version I have of the same file, it's given an allocation via malloc.  I would expect dhrystone to fail if Ptr_Glob does not point to a valid memory location.

**Comment by wyvernSemi** [comment]
This issue should be closed by now. I debugged the fault some weeks ago due to a modification to the dhrystone code (see my last comment). I have had no feedback on whether this was corrected.

**Comment by chili-chips-ba** [comment]
@tarik-ibrahimovic, have you tried it with Simon's correction? 

If this original problem is no more, and there are no follow up comments or questions, please proceed with closing this issue.

**Comment by tarik-ibrahimovic** [comment]
Confirmed, this does fix the issue.
